version: '3'
services:

  parking-lot-service:
    image: parking-lot-service:latest
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 8596
      DB_NAME: parklotdb

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: parklotdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8596
    ports:
      - "5432:5432"